@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}


# @name create_organization
POST {{baseUrl}}/orgs
Content-Type: application/json

{
    "name": "Organization Name",
    "ownerName": "John Doe",
    "email": "organization@email.com",
    "password": "123456",
    "phone": "123456789",
    "cep": "12345678",
    "street": "Organization Street",
    "number": "123",
    "neighborhood": "Organization Neighborhood",
    "city": "Organization City",
    "state": "Organization State",
    "longitude": 123.456,
    "latitude": 123.456
}

###

# @name authenticate
POST {{baseUrl}}/orgs/auth
Content-Type: application/json

{
    "email": "organization@email.com",
    "password": "123456"
}

###

# @name register-pet
POST {{baseUrl}}/orgs/pets
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "petName": "Pet Name",
    "about": "About",
    "age": "10",
    "size": "10",
    "energy_level": "10",
    "environment": "10"
}
